# Pre-commit configuration file
# this file does not yet include type checking with mypy or ty which needs to be added
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '^(?!.*\.py$).*'
      - id: trailing-whitespace
        exclude: '^(?!.*\.py$).*'
      - id: mixed-line-ending
        exclude: '^(?!.*\.py$).*'
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache, --verbose]
        exclude: '^(?!.*\.py$).*'
      - id: ruff-format
        args: [--verbose]
        exclude: '^(?!.*\.py$).*'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: '^(?!.*\.py$).*'